### ISSUE TITLE
nfsbroker can push to cf/249, diego/1.0.0, nfs-volume/1.0.6 

### ISSUE THREAD

**Issue by ron4git** [cloudfoundry/volman#3]
I am trying to push nfsbroker as cf app. 
The app builds fine, and pushed to cf without problem. However, it failed to start with/without cf bind to postgresql service instantances.

cf logs nfsbroker --recent showing following error:

2017-08-22T12:09:28.67-0700 [APP/PROC/WEB/0] OUT Exit status 2
2017-08-22T12:09:28.68-0700 [CELL/0] OUT Exit status 0
2017-08-22T12:09:28.70-0700 [CELL/0] OUT Destroying container
2017-08-22T12:09:28.72-0700 [CELL/0] OUT Creating container
2017-08-22T12:09:28.97-0700 [CELL/0] OUT Successfully destroyed container
2017-08-22T12:09:29.01-0700 [CELL/0] OUT Successfully created container
2017-08-22T12:09:29.23-0700 [CELL/0] OUT Starting health monitoring of container
2017-08-22T12:09:29.34-0700 [APP/PROC/WEB/0] OUT {"data":{},"log_level":1,"message":"nfsbroker.starting","source":"nfsbroker","timestamp":"1503428969.341427565"}
2017-08-22T12:09:29.34-0700 [APP/PROC/WEB/0] OUT {"data":{"error":"VCAP_SERVICES missing specified db service","stuff":{},"trace":"goroutine 1 [running]:\ncode.cloudfoundry.org/lager.(*logger).Fatal(0xc42012e3c0, 0x8a2aa6, 0x17, 0xa752c0, 0xc420126f10, 0xc420128128, 0x1, 0x1)\n\t/home/rliu/manifest/nfs-volume-release/src/code.cloudfoundry.org/lager/logger.go:131 +0xc7\nmain.parseVcapServices(0xa7d980, 0xc42012e3c0)\n\t/home/rliu/manifest/nfs-volume-release/src/code.cloudfoundry.org/nfsbroker/main.go:172 +0x911\nmain.createServer(0xa7d980, 0xc42012e3c0, 0xc42012e3c0, 0x89491b)\n\t/home/rliu/manifest/nfs-volume-release/src/code.cloudfoundry.org/nfsbroker/main.go:192 +0x77e\nmain.main()\n\t/home/rliu/manifest/nfs-volume-release/src/code.cloudfoundry.org/nfsbroker/main.go:118 +0x1bc\n"},"log_level":3,"message":"nfsbroker.missing-service-binding","source":"nfsbroker","timestamp":"1503428969.341789722"}
2017-08-22T12:09:29.34-0700 [APP/PROC/WEB/0] OUT {"data":{},"log_level":1,"message":"nfsbroker.ends","source":"nfsbroker","timestamp":"1503428969.341918468"}
2017-08-22T12:09:29.34-0700 [APP/PROC/WEB/0] ERR panic: VCAP_SERVICES missing specified db service
2017-08-22T12:09:29.34-0700 [APP/PROC/WEB/0] ERR goroutine 1 [running]:
2017-08-22T12:09:29.34-0700 [APP/PROC/WEB/0] ERR code.cloudfoundry.org/lager.(*logger).Fatal(0xc42012e3c0, 0x8a2aa6, 0x17, 0xa752c0, 0xc420126f10, 0xc420128128, 0x1, 0x1)
2017-08-22T12:09:29.34-0700 [APP/PROC/WEB/0] ERR        /home/user1/manifest/nfs-volume-release/src/code.cloudfoundry.org/lager/logger.go:152 +0x40a
2017-08-22T12:09:29.34-0700 [APP/PROC/WEB/0] ERR main.parseVcapServices(0xa7d980, 0xc42012e3c0)
2017-08-22T12:09:29.34-0700 [APP/PROC/WEB/0] ERR        /home/user1/manifest/nfs-volume-release/src/code.cloudfoundry.org/nfsbroker/main.go:172 +0x911
2017-08-22T12:09:29.34-0700 [APP/PROC/WEB/0] ERR main.createServer(0xa7d980, 0xc42012e3c0, 0xc42012e3c0, 0x89491b)
2017-08-22T12:09:29.34-0700 [APP/PROC/WEB/0] ERR        /home/user1/manifest/nfs-volume-release/src/code.cloudfoundry.org/nfsbroker/main.go:192 +0x77e
2017-08-22T12:09:29.34-0700 [APP/PROC/WEB/0] ERR main.main()
2017-08-22T12:09:29.34-0700 [APP/PROC/WEB/0] ERR        /home/user1/manifest/nfs-volume-release/src/code.cloudfoundry.org/nfsbroker/main.go:118 +0x1bc

manifest.yml

---
  buildpack: binary_buildpack
  env:
    SERVICENAME: nfs #service name to publish in the marketplace
    USERNAME: admin
    PASSWORD: goodpassword
    LOGLEVEL: info #error, warn, info, debug
    DBDRIVERNAME: postgres #mysql or postgres

    # if the database is provided via cf bind, DBSERVICENAME must be set otherwise
    # it should be omitted and the other db connection parameters should be set.
    DBSERVICENAME: postgresql #service name for db service as seen in `cf marketplace`
    ALLOWED_OPTIONS: "uid,gid,auto_cache,username,password"

#   DBHOST: 10.4.4.4
#   DBPORT: 9999
#   DBNAME: something
#   DB_USERNAME: something
#   DB_PASSWORD: something

**Comment by julian-hj** [comment]
Hi @ron4git : a couple things:
1) it looks like the environment in VCAP_SERVICES does not contain a service called "postgresql" as you have specified in your environment.  Can you check `cf env` for your broker app to verify?
2) This is decidedly not an issue with volman.  If you require more help with this issue, can you open an issue against [nfs-volume-release](https://github.com/cloudfoundry/nfs-volume-release) or [nfsbroker](https://github.com/cloudfoundry/nfsbroker) and close this one?  Thanks!

**Comment by ron4git** [comment]
Hi Julian-hj,
The previous log I attached were obtained when I was trying to start after unbind the postgresql service instances.  It failed to start with or without bind to the postgresql service instances. Here is the log when I tried to start the app after cf bind to the postgresql service instances. 

2017-08-22T14:37:54.64-0700 [APP/PROC/WEB/0] OUT Exit status 2
2017-08-22T14:37:54.66-0700 [CELL/0] OUT Exit status 0
2017-08-22T14:37:54.67-0700 [CELL/0] OUT Destroying container
2017-08-22T14:37:54.69-0700 [CELL/0] OUT Creating container
2017-08-22T14:37:54.95-0700 [CELL/0] OUT Successfully destroyed container
2017-08-22T14:37:54.99-0700 [CELL/0] OUT Successfully created container
2017-08-22T14:37:55.21-0700 [CELL/0] OUT Starting health monitoring of container
2017-08-22T14:37:55.30-0700 [APP/PROC/WEB/0] OUT {"data":{},"log_level":1,"message":"nfsbroker.starting","source":"nfsbroker","timestamp":"1503437875.308967352"}
2017-08-22T14:37:55.30-0700 [APP/PROC/WEB/0] OUT {"data":{},"log_level":1,"message":"nfsbroker.ends","source":"nfsbroker","timestamp":"1503437875.309250116"}
2017-08-22T14:37:55.31-0700 [APP/PROC/WEB/0] ERR panic: interface conversion: interface {} is string, not float64
2017-08-22T14:37:55.31-0700 [APP/PROC/WEB/0] ERR goroutine 1 [running]:
2017-08-22T14:37:55.31-0700 [APP/PROC/WEB/0] ERR main.parseVcapServices(0xa7d980, 0xc42001e420)
2017-08-22T14:37:55.31-0700 [APP/PROC/WEB/0] ERR        /home/user01/manifest/nfs-volume-release/src/code.cloudfoundry.org/nfsbroker/main.go:183 +0x65d
2017-08-22T14:37:55.31-0700 [APP/PROC/WEB/0] ERR main.createServer(0xa7d980, 0xc42001e420, 0xc42001e420, 0x89491b)
2017-08-22T14:37:55.31-0700 [APP/PROC/WEB/0] ERR        /home/user01/manifest/nfs-volume-release/src/code.cloudfoundry.org/nfsbroker/main.go:192 +0x77e
2017-08-22T14:37:55.31-0700 [APP/PROC/WEB/0] ERR main.main()
2017-08-22T14:37:55.31-0700 [APP/PROC/WEB/0] ERR        /home/user01/manifest/nfs-volume-release/src/code.cloudfoundry.org/nfsbroker/main.go:118 +0x1bc
2017-08-22T14:37:55.31-0700 [APP/PROC/WEB/0] OUT Exit status 2
2017-08-22T14:37:55.32-0700 [CELL/0] OUT Exit status 0
2017-08-22T14:37:55.33-0700 [CELL/0] OUT Destroying container
2017-08-22T14:37:55.61-0700 [CELL/0] OUT Successfully destroyed container

Thanks
Ron
